name: PADI Ontology Validator
on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install pySHACL
        run: pip install pyshacl

      - name: Run PADI Validation
        run: |
          pyshacl padi.ttl -s padi.shacl -m human -f table
